---
# Tasks for Nginx installation and setup
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Obtain Let's Encrypt certificate
  command: >
    certbot certonly --nginx -n --agree-tos
    --email admin@example.com
    -d example.com -d www.example.com
  become: yes
  args:
    creates: /etc/letsencrypt/live/lastdance.com/fullchain.pem


- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Deploy custom Nginx config for domain
  template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload Nginx
  become: yes
