[wordpress_servers]
# Add your AWS EC2 instance IPs here
# Example: 
# 54.123.456.789 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/your-key.pem

54.160.195.113 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ansible-key.pem

[wordpress_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root
ansible_become_pass=