---
- hosts: all
  become: yes
  vars:
    mysql_root_password: "rootpassword"
    wordpress_db_name: "wordpress"
    wordpress_db_user: "wpuser"
    wordpress_db_password: "wppassword"
    phpmyadmin_setup: true
  roles:
    - mysql
    - nginx
    - phpmyadmin
    - wordpress
     - firewall
