---
galaxy_info:
  author: Chaimaa
  description: Install Docker and Docker Compose
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - docker
    - container

dependencies: []